name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Tag, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t aidansaccount2004/my-img-k8s:latest .

      - name: Tag Docker image with Git commit SHA
        run: docker tag aidansaccount2004/my-img-k8s:latest aidansaccount2004/my-img-k8s:${{ github.sha }}

      - name: Configure Docker credentials
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login aidansaccount2004 -u aidansaccount2004 --password-stdin

      - name: Push Docker image to registry
        run: docker push aidansaccount2004/my-img-k8s:${{ github.sha }}

  list:
    name: List Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Docker images
        run: docker images

  security_scan:
    name: Dockerfile Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s)_$(uname -m).deb
          sudo dpkg -i trivy_$(uname -s)_$(uname -m).deb

      - name: Run Dockerfile security scan
        run: trivy --exit-code 1 --severity HIGH,MEDIUM --no-progress .

      - name: Scan Docker image
        run: trivy --exit-code 1 --severity HIGH,MEDIUM --no-progress aidansaccount2004/my-img-k8s:${{ github.sha }}
