name: Build and Push Docker image to GAR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: charming-study-382702
  GAR_LOCATION: us-central1
  REPOSITORY: for-hello-chart
  IMAGE: img-kuber

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --tag "gcr.io/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" .

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: "350.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY_PROJ }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate Docker to Google Artifact Registry
        run: |
          echo ${{ secrets.GCP_SA_KEY_PROJ }} | base64 --decode > key.json
          docker login -u _json_key --password-stdin https://${{ env.GAR_LOCATION}}-docker.pkg.dev < key.json

      - name: Push Docker image to GAR
        run: docker push "gcr.io/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
