name: Build and Push Docker image to GAR

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: charming-study-382702
  GAR_LOCATION: us-central1
  REPOSITORY: for-hello-chart
  IMAGE: img-kuber

jobs:
  build-and-push:
    name: Docker build, tag, and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker build
        run: docker build --tag "${GAR_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROJ }}
          token_format: access_token

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker push
        run: docker push "${GAR_LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
